### ISSUE TITLE
drop 'about' elements 

### ISSUE THREAD

**Issue by cboettig** [cboettig/nexld#6]
In JSON-LD, the parent element is implicit in the nesting.  Since we unnest meta elements anyway to make their `property`/`rel` attributes direct children, the `about` element is redundant. 

Of course this is something of a nuisance as we will need to put it back when we go from jsonld -> nexml.  

Note that technically we are currently relying on the nesting of meta elements within their XML parent when we expand meta elements; e.g. 

```xml
<otu id="VTO_0065870" label="Xenurobrycon macropus" about="#VTO_0065870">
      <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0065870" />
</otu>
```

becomes

```json
{
        "@type": "otu",
        "@id": "VTO_0065870",
        "label": "Xenurobrycon macropus",
        "about": "#VTO_0065870",
        "dwc:taxonID": "http://purl.obolibrary.org/obo/VTO_0065870"
}
```

while in RDFa, the meta element technically describes whatever parent sets the `about` context and not necessarily its immediate parent.

**Comment by rvosa** [comment]
Agreed: AFAIC we should discard everything that's just RDFa syntax hoops we have to jump through in the (Ne)XML context. The goal should be idiomatic, concise JSON-LD - provided this can be roundtrippped back to NeXML.

**Comment by sckott** [comment]
working on this on a branch
