### ISSUE TITLE
`as_list` overriding `xml2`

### ISSUE THREAD

**Issue by sckott** [cboettig/nexld#8]
is it perhaps better to use a diff. fxn name instead of overriding `xml2::as_list`?  maybe there's a good reason for it though

**Comment by cboettig** [comment]
yeah, good call, we should use a different function name

**Comment by cboettig** [comment]
I've renamed those methods to be `as_nexld`. They aren't exported as generics, so just for internal use still.  It might be nice to define `nexld` an S3 class for this list object too, which would help clarify the distinction between the R representation (`list`, as returned by `parse_nexml()` currently, which probably needs a better name) and an external serialization as json (e.g. as returned by `xml_to_json` currently, which is just `parse_nexml` + `toJSON`, though maybe should be replaced.  still figuring out a sensible user API.  

Input on names would be good too -- what do folks think of nexld?

**Comment by cboettig** [comment]
apparently my renaming was a bit premature and just broke parsing instead.  rolled back and added a less trivial test to check parsing is still getting out data.

**Comment by sckott** [comment]
i think the pkg name is good as is.
